version: '3.8'

services:
  app:
    container_name: auth-api
    build: .
    ports:
      - "3005:3004"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      AUTH_TOKEN: ${_authToken}
    volumes:
      - /usr/src/app/node_modules

  db:
    image: postgres-uniride-auth-dev 
    ports:
      - "5443:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: