version: '3.8'
services:
  app:
    container_name: auth-api
    build: 
      context: .
      target: production # Spécifie l'étape de production du Dockerfile
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      AUTH_TOKEN: ${_authToken}
    volumes:
      - /usr/src/app/node_modules
