version: '3.8'

services:
  app:
    container_name: auth-api
    build: .
    ports:
      - "3005:3004"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      AUTH_TOKEN: ${_authToken}
    volumes:
      - /usr/src/app/node_modules
