name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy project
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip << EOF
            set -e
            cd /projects/uniride
            if [ ! -d "./authService" ]; then
              git clone your_repository_URL authService
            fi
            cd authService
            git pull origin main
          EOF
