name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        run: |
          docker build --no-cache --build-arg TOKEN_REPO=${{ secrets.TOKEN_REPO }} -t ${{ secrets.DOCKER_USERNAME }}/uniride-auth-service . && \
          docker tag ${{ secrets.DOCKER_USERNAME }}/uniride-auth-service ${{ secrets.DOCKER_USERNAME }}/uniride-auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/uniride-auth-service:latest
