name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Executing remote ssh commands to deploy the application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/projects/uniride
            if [ -d "./Uniride-authService" ]; then
              cd Uniride-authService
              git fetch
              git pull origin develop
              git checkout develop
            else
              git clone https://${{ secrets.TOKEN_REPO }}:x-oauth-basic@github.com/NoSleepFullBuild/Uniride-authService.git
              cd Uniride-authService
              git fetch
              git checkout develop
            fi
            # Correction : Assurez-vous que la version de Node.js est vérifiée dans le conteneur Docker et non sur le serveur hôte
            docker-compose down
            docker-compose build --no-cache auth_service
            # Exécutez cette commande pour vérifier la version de Node dans le conteneur nouvellement construit
            docker run --rm your-service-name node -v
            docker-compose up -d
